[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000000
verbosity = 1
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
cbor_metadata = true

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[etherscan]
base_sepolia = { key = "${BASE_SEPOLIA_ETHERSCAN_API_KEY}" }
