[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000000
verbosity = 1
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
cbor_metadata = true
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
base_sepolia = "${BASE_SEPOLIA_RPC_URL}"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[etherscan]
#unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 84532, url = "https://api.tenderly.co/api/v1/account/superform/project/v1/etherscan/verify/network/84532/public" }
