[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000000
verbosity = 1
remappings = ["@openzeppelin/contracts/=lib/openzeppelin-contracts/contracts/"]
cbor_metadata = true
fs_permissions = [{ access = "read-write", path = "./" }]

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true

[etherscan]
#                   Paste TENDERLY_ACCESS_TOKEN            Chain ID         Verifier URL: RPC_URL/verify/etherscan
unknown_chain = { key = "${TENDERLY_ACCESS_KEY}", chain = 8453, url = "${BASE_VERIFIER_URL}" }
