[profile.default]
solc_version = "0.8.28"
optimizer = true
optimizer_runs = 1000000
verbosity = 1

[rpc_endpoints]
base = "${BASE_RPC_URL}"

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
