name: "Smart Contracts CI"

env:
  API_KEY_ALCHEMY: ${{ secrets.API_KEY_ALCHEMY }}
  FOUNDRY_PROFILE: "ci"
  BSC_RPC_URL: ${{ secrets.BSC_RPC_URL }}
  ARBITRUM_RPC_URL: ${{ secrets.ARBITRUM_RPC_URL }}
  OPTIMISM_RPC_URL: ${{ secrets.OPTIMISM_RPC_URL }}
  ETHEREUM_RPC_URL: ${{ secrets.ETHEREUM_RPC_URL }}
  POLYGON_RPC_URL: ${{ secrets.POLYGON_RPC_URL }}
  AVALANCHE_RPC_URL: ${{ secrets.AVALANCHE_RPC_URL }}
  BASE_RPC_URL: ${{ secrets.BASE_RPC_URL }}
  FANTOM_RPC_URL: ${{ secrets.FANTOM_RPC_URL }}
  LINEA_RPC_URL: ${{ secrets.LINEA_RPC_URL }}
  BLAST_RPC_URL: ${{ secrets.BLAST_RPC_URL }}
  BSC_RPC_URL_QN: ${{ secrets.BSC_RPC_URL }}
  ARBITRUM_RPC_URL_QN: ${{ secrets.ARBITRUM_RPC_URL }}
  OPTIMISM_RPC_URL_QN: ${{ secrets.OPTIMISM_RPC_URL }}
  ETHEREUM_RPC_URL_QN: ${{ secrets.ETHEREUM_RPC_URL }}
  POLYGON_RPC_URL_QN: ${{ secrets.POLYGON_RPC_URL }}
  AVALANCHE_RPC_URL_QN: ${{ secrets.AVALANCHE_RPC_URL }}
  BASE_RPC_URL_QN: ${{ secrets.BASE_RPC_URL }}
  FANTOM_RPC_URL_QN: ${{ secrets.FANTOM_RPC_URL }}
  LINEA_RPC_URL_QN: ${{ secrets.LINEA_RPC_URL }}
  BLAST_RPC_URL_QN: ${{ secrets.BLAST_RPC_URL }}
  TENDERLY_ACCESS_KEY: ${{ secrets.TENDERLY_ACCESS_KEY }}
  TENDERLY_PROJECT_SLUG: "v1" # your project slug
  TENDERLY_ACCOUNT_ID: "piggy" # your username or organization name
  FOUNDRY_EXPORTS_OVERWRITE_LATEST: "true"
  OWNER_ADDRESS: ${{ secrets.OWNER_ADDRESS }}
  DEBUG_MODE: "false"

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: "SuperformCore3"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "latest"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Foundry dependencies"
        run: forge install

      - name: "Build the contracts and print their size"
        run: "forge build"

      - name: "Add build summary"
        run: |
          echo "## Build result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY

  test:
    needs: ["build"]
    runs-on: "SuperformCore3"
    steps:
      - name: "Check out the repo"
        uses: "actions/checkout@v4"

      - name: "Install node"
        uses: "actions/setup-node@v3"
        with:
          node-version: "latest"

      - name: "Install Foundry"
        uses: "foundry-rs/foundry-toolchain@v1"

      - name: "Install Foundry dependencies"
        run: forge install

      - name: "Show the Foundry config"
        run: "forge config"

      - name: "Generate a fuzz seed that changes weekly to avoid burning through RPC allowance"
        run: >
          echo "FOUNDRY_FUZZ_SEED=$(
            echo $(($EPOCHSECONDS - $EPOCHSECONDS % 604800))
          )" >> $GITHUB_ENV

      - name: "Run the tests"
        run: "forge test"

      - name: "Add test summary"
        run: |
          echo "## Tests result" >> $GITHUB_STEP_SUMMARY
          echo "✅ Passed" >> $GITHUB_STEP_SUMMARY
